"use client";
import {ProductPrice} from "./product-price";
import {ThemeToggle} from "./theme";
import {createContext,useContext,useEffect,useState,useRef,ReactNode} from "react";import Link from "next/link";import Image from "next/image";import {Check,ShoppingBag,Search,Menu,Plus,Minus,ArrowRight,Trash2,MessageCircle} from "lucide-react";import {Sheet,SheetContent,SheetTitle,SheetDescription} from "@/components/ui/sheet";import {products,categories} from "@/lib/catalog";import {site,whatsappReady} from "@/lib/config";
export type CartItem={id:string;quantity:number;variant?:string};type CartContext={items:CartItem[];ready:boolean;add:(id:string,q?:number,open?:boolean)=>void;update:(id:string,q:number)=>void;clear:()=>void;setOpen:(v:boolean)=>void};const Context=createContext<CartContext|null>(null);export function useCart(){return useContext(Context)!}
export function StoreProvider({children}:{children:ReactNode}){const [items,setItems]=useState<CartItem[]>([]),[ready,setReady]=useState(false),[open,setOpen]=useState(false);useEffect(()=>{let active=true;queueMicrotask(()=>{if(!active)return;try{const raw=JSON.parse(localStorage.getItem("magnet-cart")||"[]");if(Array.isArray(raw)){const merged=new Map<string,number>();raw.forEach(i=>{if(i && typeof i === "object" && products.some(p=>p.id===i.id)&&Number.isInteger(i.quantity)&&i.quantity>0)merged.set(i.id,Math.min(99,(merged.get(i.id)||0)+i.quantity))});setItems(Array.from(merged,([id,quantity])=>({id,quantity})))}}catch{}setReady(true)});return ()=>{active=false}},[]);useEffect(()=>{if(ready)try{localStorage.setItem("magnet-cart",JSON.stringify(items))}catch{}},[items,ready]);const add=(id:string,q=1,show=true)=>{if(!products.some(p=>p.id===id))return;const qty=Math.max(1,Math.min(99,Math.floor(q)||1));setItems(old=>old.some(i=>i.id===id)?old.map(i=>i.id===id?{...i,quantity:Math.min(99,i.quantity+qty)}:i):[...old,{id,quantity:qty}]);if(show)setOpen(true)};const update=(id:string,q:number)=>setItems(old=>q<1?old.filter(i=>i.id!==id):old.map(i=>i.id===id?{...i,quantity:Math.min(99,Math.floor(q)||1)}:i));return <Context.Provider value={{items,ready,add,update,clear:()=>setItems([]),setOpen}}>{children}<Sheet open={open} onOpenChange={setOpen}><SheetContent className="cart-sheet"><SheetTitle>Your basket</SheetTitle><SheetDescription>Good food starts here.</SheetDescription><div className="drawer-items"><CartLines/></div>{items.length>0&&<><p>{site.deliveryNote}</p><Link className="button" href="/checkout" onClick={()=>setOpen(false)}>Continue to checkout <ArrowRight size={18}/></Link><Link className="text-link" href="/cart" onClick={()=>setOpen(false)}>View full basket</Link></>}<button className="text-link" onClick={()=>setOpen(false)}>Continue shopping</button></SheetContent></Sheet></Context.Provider>}
export function AddButton({id,compact=false,quantity=1}:{id:string;compact?:boolean;quantity?:number}) {
  const {add,ready,items}=useCart();
  const [added,setAdded]=useState(false);
  const timer=useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
  const atLimit=(items.find(item=>item.id===id)?.quantity??0)>=99;
  return <button disabled={!ready||atLimit} className={`${compact?"quick-add":"button"}${added?" just-added":""}`} onClick={()=>{add(id,quantity,false);setAdded(true);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setAdded(false),1600)}} aria-label={atLimit?"Maximum quantity reached":`Add ${products.find(p=>p.id===id)?.name} to basket`}>
    {added?<Check size={18}/>:<Plus size={18}/>}<span role="status" aria-live="polite">{added?"Added!":atLimit?"Max 99":compact?"Add":"Add to basket"}</span>
  </button>
}
export function Header(){const {items,setOpen}=useCart(),[menu,setMenu]=useState(false);return <><div className="announcement">{site.announcement}<ArrowRight size={13}/></div><header className="header wrap"><Link href="/" aria-label="Magnet Masala home"><Image src="/logo.jpg" width={78} height={78} alt="Magnet Masala" className="logo" priority/></Link><nav className="desktop-nav"><Link href="/shop">Shop all</Link><Link href="/#bundles">Bundles</Link><Link href="/about">Our story</Link><Link href="/contact">Contact</Link></nav><div className="header-actions"><ThemeToggle/><Link href="/shop?search=" aria-label="Search products"><Search/></Link><button aria-label="Open cart" onClick={()=>setOpen(true)}><ShoppingBag/><span className="badge basket-bounce" key={items.reduce((s,i)=>s+i.quantity,0)} aria-live="polite" aria-atomic="true">{items.reduce((s,i)=>s+i.quantity,0)}</span></button><button className="mobile-menu" aria-label="Open navigation" onClick={()=>setMenu(true)}><Menu/></button></div></header><Sheet open={menu} onOpenChange={setMenu}><SheetContent><SheetTitle>Magnet Masala</SheetTitle><SheetDescription>Find your next favourite masala.</SheetDescription><nav className="mobile-links">{[["Shop all","/shop"],["Categories","/#categories"],["Bundles","/#bundles"],["Our story","/about"],["Contact","/contact"],["Your basket","/cart"]].map(([n,h])=><Link key={h} href={h} onClick={()=>setMenu(false)}>{n}</Link>)}</nav></SheetContent></Sheet></>}
export function Quantity({value,onChange}:{value:number;onChange:(n:number)=>void}){return <div className="quantity"><button aria-label="Decrease quantity" disabled={value<=1} onClick={()=>onChange(value-1)}><Minus size={16}/></button><output aria-label="Quantity">{value}</output><button aria-label="Increase quantity" disabled={value>=99} onClick={()=>onChange(value+1)}><Plus size={16}/></button></div>}
export function CartLines(){const {items,update,ready,setOpen}=useCart();if(!ready)return <p>Loading your basket…</p>;if(!items.length)return <div className="empty"><ShoppingBag size={38}/><h2>Your kitchen needs a little more flavour.</h2><Link href="/shop" className="button" onClick={()=>setOpen(false)}>Explore Magnet Masala</Link></div>;return <>{items.map(i=>{const p=products.find(p=>p.id===i.id)!;return <div className="cart-line" key={i.id}><Link href={`/products/${p.slug}`}><Image src={p.image} width={86} height={110} alt={p.name}/></Link><div><Link href={`/products/${p.slug}`}><h3>{p.name}</h3></Link><p className="muted">{p.weight}</p><ProductPrice product={p}/><Quantity value={i.quantity} onChange={q=>update(i.id,q)}/>{p.price!==null&&<p>Rs. {(p.price*i.quantity).toLocaleString()}</p>}</div><button className="remove" aria-label={`Remove ${p.name}`} onClick={()=>update(i.id,0)}><Trash2 size={18}/></button></div>})}</>}
export function Footer(){return <footer><div className="wrap footer-grid"><div><Image src="/logo.jpg" width={104} height={104} alt="Magnet Masala" className="footer-logo"/><p>Everyday spices. Favourite recipes.<br/>One kitchen shelf.</p></div><div><h3>Shop</h3><Link href="/shop">All products</Link><Link href="/#bundles">Curated bundles</Link>{categories.map(c=><Link key={c} href={`/shop?category=${encodeURIComponent(c)}`}>{c}</Link>)}</div><div><h3>Good to know</h3>{["About","Delivery","FAQ","Contact"].map(n=><Link key={n} href={'/'+n.toLowerCase()}>{n==="About"?"Our story":n}</Link>)}</div><div><h3>Let’s talk flavour</h3><p>Questions about your order?<br/>We’re happy to help.</p><Link href="/contact" className="footer-contact">Get in touch <ArrowRight size={16}/></Link>{whatsappReady&&<a href={`https://wa.me/${site.whatsapp}`}><MessageCircle size={16}/> WhatsApp</a>}{site.email&&<a href={`mailto:${site.email}`} style={{overflowWrap:"anywhere"}}>{site.email}</a>}{site.instagram&&<a href={site.instagram}>Instagram</a>}{site.facebook&&<a href={site.facebook}>Facebook</a>}</div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} Magnet Masala</span><div><Link href="/privacy">Privacy policy</Link><Link href="/terms">Terms</Link></div><span>Made for the love of food.</span></div></footer>}
